[package]
name = "iii-example"
version = "0.0.0"
edition = "2024"

[dependencies]
iii-sdk = { path = "../iii" }
serde_json = "1"
serde = { version = "1", features = ["derive"] }
tokio = { version = "1", features = ["macros", "rt-multi-thread", "time"] }

